// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlyGj7YQ3XHfOUQSHVsg8_2pheA6pvjPI',
    appId: '1:697070371727:web:54b66a9e976a44642941fa',
    messagingSenderId: '697070371727',
    projectId: 'fir-logsign-8f537',
    authDomain: 'fir-logsign-8f537.firebaseapp.com',
    storageBucket: 'fir-logsign-8f537.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk-fObix9bifGgclm-svLD4S0p46IfFt0',
    appId: '1:697070371727:android:21fde22cc8c844eb2941fa',
    messagingSenderId: '697070371727',
    projectId: 'fir-logsign-8f537',
    storageBucket: 'fir-logsign-8f537.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAMN8eCkT86PM6APOkLnumfxtwFpVtwAk',
    appId: '1:697070371727:ios:059b94aba15b97902941fa',
    messagingSenderId: '697070371727',
    projectId: 'fir-logsign-8f537',
    storageBucket: 'fir-logsign-8f537.appspot.com',
    iosBundleId: 'com.example.firebaseLogsign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAMN8eCkT86PM6APOkLnumfxtwFpVtwAk',
    appId: '1:697070371727:ios:c1ecd9dfd50264722941fa',
    messagingSenderId: '697070371727',
    projectId: 'fir-logsign-8f537',
    storageBucket: 'fir-logsign-8f537.appspot.com',
    iosBundleId: 'com.example.firebaseLogsign.RunnerTests',
  );
}
